name: Stock Market Kakao Briefing

on:
  workflow_dispatch:

  schedule:
    - cron: "0 22 * * *"
    - cron: "0 2 * * *"
    - cron: "0 7 * * *"
    - cron: "0 10 * * *"

jobs:
  stock-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pytz requests yfinance pykrx

      - name: Run stock briefing script
        env:
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
        run: |
          echo "한국시간:"
          TZ=Asia/Seoul date

          echo "stock_bot.py 실행"
          python stock_bot.py

      - name: Success
        if: success()
        run: |
          echo "카카오 주식 브리핑 전송 성공"

      - name: Failure
        if: failure()
        run: |
          echo "카카오 주식 브리핑 전송 실패"
